<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorTechNotes.Domain\BlazorTechNotes.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="Features\Users\GetUserRoles\" />
  </ItemGroup>

</Project>
